### ISSUE TITLE
Unable to download extension from GNOME Extensions on GNOME 46

### ISSUE THREAD

**Issue by Keanu73** [sidevesh/solaar-extension-for-gnome#5] opened 2024-04-24 17:05 UTC
Hi there,
I recently upgraded to Fedora 40 which uses GNOME 46. I notice you updated the extension's metadata to support version 46, however it seems this isn't reflected in the store. Could you fix this? Thanks :)

**Comment by PlatyBZH** [comment] 2024-05-11 14:10
Same issue as @Keanu73 
After upgrading to gnome 46, the extension does not work unless I check "disable-version-extension-validation" in dconf-editor.

`gsettings set org.gnome.shell disable-extension-version-validation true`

**Comment by sidevesh** [comment] 2024-05-12 03:50
I have not been able to test out the extension on Gnome 46 yet, although I have updated the extension for 46 and you can download it from the Releases tab on GitHub.
I have also pushed the update version to GNOME extensions today,
it would be great if someone can test it out and let me know if things are working okay.

**Comment by PlatyBZH** [comment] 2024-05-12 08:15
The extension is now working as expected for me in gnome 46 on fedora 40, from the official GNOME extensions repository. Thanks for your quick fix !

I'd be happy to test things out more extensively for you if you need, if you have a process or specific rules you want to try (I have a logitech G915 Keyboard and a MX Master 3S Mouse)

**Comment by sidevesh** [comment] 2024-05-12 09:21
the two conditions that the extension enables on Wayland are active window and mouse over window.
Sounds like active window is working so it's mouse over window that needs to be confirmed.
Would be great if you can test that.

**Comment by sidevesh** [comment] 2024-05-12 11:04
Closing this since the extension is now available from GNOME Extensions

**Closed by sidevesh** 2024-05-12 11:04 UTC
